<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Abaddax.$(MSBuildProjectName)</RootNamespace>
    <AssemblyName>Abaddax.$(MSBuildProjectName)</AssemblyName>
    <PackageId>Abaddax.$(MSBuildProjectName)</PackageId>
    <TargetFrameworks>net10.0;net9.0;net8.0</TargetFrameworks>
    <Version>0.1.6</Version>
    <Description>SOCKS5 client/server implemented in .NET</Description>
    <Authors>Abaddax</Authors>
    <RepositoryUrl>https://github.com/Abaddax/Socks5.git</RepositoryUrl>
    <ExternalPackageLicenseFile>../LICENSE</ExternalPackageLicenseFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Abaddax.Utilities" Version="0.1.6" />
    <PackageReference Include="Abaddax.Build.Common" Version="0.0.1-preview6">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
